[package]
name = "ottr"
version = "0.1.0"
edition = "2021"

[lib]
name = "ottr"
path = "src/lib.rs"

[[bin]]
name = "cantilever_sin_load"
path = "bin/cantilever_sin_load.rs"

[dependencies]
approx = "0.5.1"
faer = "0.19.4"
gauss-quad = "0.2.1"
itertools = "0.13.0"
vtkio = "0.6.3"
